### ISSUE TITLE
Wont Install

### ISSUE THREAD

**Issue by masterdome** [alfonsojon/roblox-linux-wrapper#29]
When I Ran The One Line Code It Said wine closed unsuccessfully.
See terminal for details. (exit code 1)

OS: Elementary Luna 12.04

**Comment by masterdome** [comment]
I have wine and gecko installed

**Comment by stormchaser3000** [comment]
i have the same issue here is some debug info:
stormchaser30000@stormchaser30000-HP-ProBook-4540s:~$ cd .rlw
stormchaser30000@stormchaser30000-HP-ProBook-4540s:~/.rlw$ ./rlw-stub.sh
zenity installed, continuing
shasum installed, continuing
wget installed, continuing

(zenity:4167): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
cat: /home/stormchaser30000/.rlw/update.ignored: No such file or directory
Loading rlw.sh ...

Roblox Linux Wrapper v20150131-staging
rmdir: failed to remove ‘/home/stormchaser30000/.local/share/wineprefixes/roblox-wine-staging’: Directory not empty

(zenity:4190): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
fixme:winediag:start_process Wine Staging is a testing version containing experimental patches.
fixme:winediag:start_process Please report bugs at http://bugs.wine-staging.com (instead of winehq.org).
regsvr32: Failed to load DLL ''
wine closed unsuccessfully.
See terminal for details. (exit code 1)

(zenity:4224): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
stormchaser30000@stormchaser30000-HP-ProBook-4540s:~/.rlw$

**Comment by alfonsojon** [comment]
Try running ROBLOX again, and it should work.

**Comment by alfonsojon** [comment]
I will release a fix for this shortly

**Comment by Mortemire** [comment]
Same thing is happening for me, I try have wine and it says the exact same thing.

I'm fourteen though, and not an expert at the terminal, I think I did it all right though.

**Comment by stormchaser3000** [comment]
i am 14. i have a lot of knowladge of the terminal. XD. just look up some totorials online or talk to other people who have a !@#$ ton of expirience

**Comment by martywd** [comment]
I don't know what others are 'seeing', but for me the latest update of rlw-stub.sh is launching roblox player and roblox studio now without errors.

Caveat:  I don't 'play' roblox myself, but have 'rlw' installed (LM 17.1 MATE 64-bit) on a couple of Desktop machines so my grandkids can play when visiting.

Thanks, alfonsojon, for your continued work and updating of this project!
.

**Comment by masterdome** [comment]
Its still not working for me

**Comment by alfonsojon** [comment]
@masterdome Try resetting it to defaults.

**Comment by alfonsojon** [comment]
This should be fixed in 20150202.

**Comment by alfonsojon** [comment]
@martywd Any time; it's my pleasure!

**Comment by masterdome** [comment]
It still does not install

**Comment by alfonsojon** [comment]
@masterdome Uninstall and reinstall, then try again. To do this, run the following command in a terminal
```WINEPREFIX=$HOME/.local/share/wineprefixes/roblox-wine-staging rm -rf $WINEPREFIX && rm -rf $HOME/.rlw```
Try again after that.

**Comment by masterdome** [comment]
@alfonsojon Still Does not work it does not uninstall it. Also it still says "wineserver closed unsuccessfully.
See terminal for details. (exit code 1)"

**Comment by alfonsojon** [comment]
@masterdome How are you installing it?

**Comment by masterdome** [comment]
@alfonsojon With the one line code

**Comment by alfonsojon** [comment]
that's strange... I'll look into that.

**Comment by masterdome** [comment]
Thanks

**Comment by Gskartwii** [comment]
I was having the same problem, but the following commands fixed it:

    sudo add-apt-repository ppa:pipelight/stable
    sudo apt-get update
    sudo apt-get install --install-recommends wine-staging

**Comment by masterdome** [comment]
@alfonsojon It still does not work for me

**Comment by masterdome** [comment]
@alfonsojon When I Install It Still Does Not Work

**Comment by masterdome** [comment]
Does anyone know how to fix this?

**Comment by alfonsojon** [comment]
Can you copy-paste what is displayed in the terminal? Thanks.

**Comment by EchoDuplication** [comment]
Roblox Linux Wrapper v20150202-staging
Roblox Linux Wrapper is not installed. This is necessary to launch games properly.
Would you like to install it?

** (zenity:20587): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-PsurvHpX8T: Connection refused

(zenity:20587): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

** (zenity:20593): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-PsurvHpX8T: Connection refused

(zenity:20593): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

** (zenity:20597): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-PsurvHpX8T: Connection refused

(zenity:20597): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

** (zenity:20601): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-PsurvHpX8T: Connection refused

(zenity:20601): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
A working Roblox wineprefix was not found. Would you like to install one?

** (zenity:20635): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-PsurvHpX8T: Connection refused

(zenity:20635): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
/dev/fd/63: line 84: --wait: command not found
wineserver closed unsuccessfully.
See terminal for details. (exit code 1)

** (zenity:20638): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-PsurvHpX8T: Connection refused

(zenity:20638): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

**Comment by alfonsojon** [comment]
@EchoDuplication Can you kindly open a terminal and run the following command? This will make a text file in your home folder, named "wine-staging-ls.txt". Please paste the contents of that file here.

Command:
```ls /opt/wine-staging/bin > $HOME/wine-staging-ls.txt```

**Comment by EchoDuplication** [comment]
ls: cannot access /opt/wine-staging/bin: No such file or directory

**Comment by alfonsojon** [comment]
Try this:
```ls /opt/wine*/bin > $HOME/wine-staging-ls.txt```

**Comment by EchoDuplication** [comment]
ls: cannot access /opt/wine*/bin: No such file or directory

**Comment by alfonsojon** [comment]
```ls /opt/ > $HOME/wine-staging-ls.txt```

**Comment by alfonsojon** [comment]
This is odd.

**Comment by EchoDuplication** [comment]
Worked but all that the text file contains is 'google'

**Comment by alfonsojon** [comment]
Thanks, I found the problem. You need to install wine-staging for Roblox Linux Wrapper to work. See this page for more info: https://github.com/wine-compholio/wine-staging/wiki/Installation

**Comment by alfonsojon** [comment]
Version 20150206 (just released) now checks to see if that is installed. It will notify you if it is not installed. Can you try it for me before you install that? Thanks.

**Comment by EchoDuplication** [comment]
Works perfectly! Thanks.

**Comment by alfonsojon** [comment]
@EchoDuplication My pleasure!

**Comment by alfonsojon** [comment]
@masterdome Does this fix the problem for you as well?

**Comment by masterdome** [comment]
@alfonsojon  Yes! Thanks For Your Help

**Comment by spedman76** [comment]
evan@evan-Latitude-D630 ~ $ bash <(wget -q https://raw.githubusercontent.com/alfonsojon/roblox-linux-wrapper/master/rlw.sh -O -)
Roblox Linux Wrapper v20150206-staging
rmdir: failed to remove `/home/evan/.local/share/wineprefixes/roblox-wine-staging': Directory not empty

(zenity:13112): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
fixme:winediag:start_process Wine Staging is a testing version containing experimental patches.
fixme:winediag:start_process Please report bugs at http://bugs.wine-staging.com (instead of winehq.org).
fixme:ntdll:NtCreateNamedPipeFile Message mode not supported, falling back to byte mode.
fixme:ntdll:NtCreateNamedPipeFile Message mode not supported, falling back to byte mode.
fixme:ntdll:NtCreateNamedPipeFile Message mode not supported, falling back to byte mode.
regsvr32: Failed to load DLL ''
wine: cannot find 'C:\Program Files\Mozilla Firefox\firefox.exe'
wine closed unsuccessfully.
See terminal for details. (exit code 1)

(zenity:13148): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

This is what i get in terminal i am useing linux mint os  can i have some help?

**Comment by spedman76** [comment]
ok i got roblox to work i can get into a server but it always crashes on me what do i do?

**Comment by Carolll** [comment]
Whats the one line command???

**Comment by alfonsojon** [comment]
@Carolll Please read the installation instructions... this issue is completely unrelated, and has been closed for months...
